
import Books.Books;
import Books.BookAction;
import User.Academician;
import User.Student;
import User.User;
import com.github.sarxos.webcam.Webcam;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.text.*;
import javax.swing.ImageIcon;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */

public class LibraryPanel extends javax.swing.JFrame {
        public static String  s;
     //User user= new User();
         
       public static String book( int bookId, String bookName, String author, String publisher, int yearOfPublication)
     {
       String bookInfo= ""+ bookId+ bookName+ author+ publisher+ yearOfPublication;
        return bookInfo;
       }
     
    
    
    
  /*   ImageIcon myIconAdmin = new ImageIcon(getClass().getResource("/images/admin.png"));
     ImageIcon myAllBooks = new ImageIcon(getClass().getResource("/images/allbooks.png"));
     //ImageIcon myCalendar = new ImageIcon(getClass().getResource("/images/Calendar.png"));
     ImageIcon myLogin = new ImageIcon(getClass().getResource("/images/login.png"));
     ImageIcon mySearch = new ImageIcon(getClass().getResource("/images/search.png"));
     //ImageIcon myLibrary = new ImageIcon(getClass().getResource("/images/Library.png"));
     
     ImageIcon myUser = new ImageIcon(getClass().getResource("/images/user.png"));
     ImageIcon myQr = new ImageIcon(getClass().getResource("/images/qr.png"));
     ImageIcon myBookGet = new ImageIcon(getClass().getResource("/images/bookGet.png"));
     ImageIcon myBookReturn = new ImageIcon(getClass().getResource("/images/bookReturn.png"));
       */
     
     
     BookAction bookAction= new BookAction();
     
    
    /**
     * Creates new form LibraryPanel
     */
    
    public LibraryPanel() {
        
        initComponents();
        
        if (User.searchUser(User.currentId) instanceof Student) {
            ta_displayuserinfo.append(Student.searchUser(User.currentId).toString());
        }
        else if (User.searchUser(User.currentId) instanceof Academician) {
             ta_displayuserinfo.append(Academician.searchUser(User.currentId).toString());
        }
        
       
        allBooks.setVisible(false); 
        removingBook.setVisible(false);
        panel_view.setVisible(false);
        
        
        
        
        //lbIcon.setIcon(myLibrary);
        /*
        label_name.setText(user.getName());
        label_surname.setText(user.getSurname());
        label_age.setText(String.valueOf(user.getAge()));
        label_gender.setText(user.getGender());
        if (user instanceof Student) {
            label_job.setText("Student");
        }
        else if (user instanceof Academician) {
            label_job.setText("Academician");
        }*/
       
      //  BookAction.addBook(new Books(01, "Pride and Prejudice", "Jane Austen", "Can", 2007));
      //  s= book(01, "Pride and Prejudice", "Jane Austen", "Can", 2007);
       
       // BookAction.addBook(new Books(02, "Nar Agacı", "Nazan Bekiroglu", "Timas", 2012));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        allBooks = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchedId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchedBookInfo = new javax.swing.JTextArea();
        addToUser = new javax.swing.JButton();
        message1 = new javax.swing.JLabel();
        jbSearch = new javax.swing.JButton();
        message3 = new javax.swing.JLabel();
        message4 = new javax.swing.JLabel();
        lbSearch = new javax.swing.JLabel();
        CloseGet = new javax.swing.JButton();
        panel_view = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_displayAllBooks = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        bt_sorting = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_alphSorting = new javax.swing.JTextArea();
        CloseView = new javax.swing.JButton();
        removingBook = new javax.swing.JPanel();
        bt_displayMyBooks = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_displayMyBook = new javax.swing.JTable();
        message2 = new javax.swing.JLabel();
        bt_return = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_dispReturnBook = new javax.swing.JTextArea();
        CloseReturn = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_displayuserinfo = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jbAddBook = new javax.swing.JButton();
        jbRemoveBook = new javax.swing.JButton();
        jbViewBooks = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Libray Automation System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LIBRARY AUTOMATION SYSTEM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        allBooks.setBackground(new java.awt.Color(235, 213, 255));
        allBooks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Search Book (Enter ID):");
        allBooks.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, -1));
        allBooks.add(searchedId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 119, -1));

        searchedBookInfo.setColumns(20);
        searchedBookInfo.setRows(5);
        searchedBookInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        jScrollPane1.setViewportView(searchedBookInfo);

        allBooks.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 210, 190));

        addToUser.setBackground(new java.awt.Color(255, 255, 255));
        addToUser.setForeground(new java.awt.Color(51, 0, 51));
        addToUser.setText("Add Book");
        addToUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToUserActionPerformed(evt);
            }
        });
        allBooks.add(addToUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 80, -1));
        allBooks.add(message1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 164, 80, 64));

        jbSearch.setBackground(new java.awt.Color(255, 255, 255));
        jbSearch.setForeground(new java.awt.Color(51, 0, 51));
        jbSearch.setText("Search");
        jbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSearchActionPerformed(evt);
            }
        });
        allBooks.add(jbSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 119, -1));
        allBooks.add(message3, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 263, 199, 35));
        allBooks.add(message4, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 311, 199, 37));
        allBooks.add(lbSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 80, 80));

        CloseGet.setBackground(new java.awt.Color(255, 255, 255));
        CloseGet.setForeground(new java.awt.Color(51, 0, 51));
        CloseGet.setText("Close");
        CloseGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseGetActionPerformed(evt);
            }
        });
        allBooks.add(CloseGet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jPanel1.add(allBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 330, 350));

        panel_view.setBackground(new java.awt.Color(235, 213, 255));
        panel_view.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_displayAllBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Book Id", "Book Name", "Author", "Publisher", "Year of Publication"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(table_displayAllBooks);

        panel_view.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 370, 100));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("LIBRARY");
        panel_view.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 136, 31));

        bt_sorting.setBackground(new java.awt.Color(255, 255, 255));
        bt_sorting.setForeground(new java.awt.Color(51, 0, 51));
        bt_sorting.setText("Sorting");
        bt_sorting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sortingActionPerformed(evt);
            }
        });
        panel_view.add(bt_sorting, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        ta_alphSorting.setColumns(20);
        ta_alphSorting.setRows(5);
        ta_alphSorting.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        jScrollPane5.setViewportView(ta_alphSorting);

        panel_view.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 206, 370, 110));

        CloseView.setText("Close");
        CloseView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseViewActionPerformed(evt);
            }
        });
        panel_view.add(CloseView, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jPanel1.add(panel_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 410, 350));

        removingBook.setBackground(new java.awt.Color(235, 213, 255));
        removingBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_displayMyBooks.setBackground(new java.awt.Color(255, 255, 255));
        bt_displayMyBooks.setForeground(new java.awt.Color(51, 0, 51));
        bt_displayMyBooks.setText("MyBooks");
        bt_displayMyBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_displayMyBooksActionPerformed(evt);
            }
        });
        removingBook.add(bt_displayMyBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        table_displayMyBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Book Id", "Book Name", "Author", "Publisher", "Year Of Publication"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_displayMyBook);

        removingBook.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 80, 350, 100));
        removingBook.add(message2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 136, 27));

        bt_return.setBackground(new java.awt.Color(255, 255, 255));
        bt_return.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_return.setForeground(new java.awt.Color(51, 0, 51));
        bt_return.setText("RETURN WITH QR CODE");
        bt_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_returnActionPerformed(evt);
            }
        });
        removingBook.add(bt_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        ta_dispReturnBook.setColumns(20);
        ta_dispReturnBook.setRows(5);
        ta_dispReturnBook.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        jScrollPane4.setViewportView(ta_dispReturnBook);

        removingBook.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 310, 80));

        CloseReturn.setBackground(new java.awt.Color(255, 255, 255));
        CloseReturn.setForeground(new java.awt.Color(51, 0, 51));
        CloseReturn.setText("Close");
        CloseReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseReturnActionPerformed(evt);
            }
        });
        removingBook.add(CloseReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 70, -1));

        jPanel1.add(removingBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 360, 350));

        ta_displayuserinfo.setColumns(20);
        ta_displayuserinfo.setRows(5);
        ta_displayuserinfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        jScrollPane6.setViewportView(ta_displayuserinfo);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 430, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 1460, 790));

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbAddBook.setBackground(new java.awt.Color(255, 255, 255));
        jbAddBook.setForeground(new java.awt.Color(51, 0, 51));
        jbAddBook.setText("Get Book");
        jbAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddBookActionPerformed(evt);
            }
        });
        jPanel2.add(jbAddBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 109, 34));

        jbRemoveBook.setBackground(new java.awt.Color(255, 255, 255));
        jbRemoveBook.setForeground(new java.awt.Color(51, 0, 51));
        jbRemoveBook.setText("Return Book");
        jbRemoveBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoveBookActionPerformed(evt);
            }
        });
        jPanel2.add(jbRemoveBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 109, 39));

        jbViewBooks.setBackground(new java.awt.Color(255, 255, 255));
        jbViewBooks.setForeground(new java.awt.Color(51, 0, 51));
        jbViewBooks.setText("View Books");
        jbViewBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbViewBooksActionPerformed(evt);
            }
        });
        jPanel2.add(jbViewBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 109, 45));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(51, 0, 51));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 109, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MAIN MENU");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddBookActionPerformed
        allBooks.setVisible(true);
     //   lbSearch.setIcon(mySearch);
    }//GEN-LAST:event_jbAddBookActionPerformed

    private void addToUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToUserActionPerformed
        String id = searchedId.getText();
        Books book = bookAction.searchBook(Integer.parseInt(id));
        User.getMyBooks().add(book);
        message1.setText("Your book is added!");
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        Date currentDate = new Date();
        Calendar gettingDate;
        
        message3.setText("Current date: " + sdf.format(currentDate));
        
        Calendar c = Calendar.getInstance();
        c.setTime(currentDate);
        
        c.add(Calendar.DATE, 15);
        
        Date returningDate = c.getTime();
        
        message4.setText("Returning date: " + sdf.format(returningDate));
        
        
        
       
        
        
    }//GEN-LAST:event_addToUserActionPerformed

    private void jbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSearchActionPerformed
        String id = searchedId.getText();
        Books book = bookAction.searchBook(Integer.parseInt(id));
        searchedBookInfo.setText(book.toString());
                
    }//GEN-LAST:event_jbSearchActionPerformed

    private void jbRemoveBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoveBookActionPerformed
        removingBook.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_jbRemoveBookActionPerformed

    private void jbViewBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbViewBooksActionPerformed
        panel_view.setVisible(true);
        int index = 0;
       
        DefaultTableModel model1 = (DefaultTableModel)table_displayAllBooks.getModel();
        
        model1.setRowCount(0);
      
        while (BookAction.book.size() > index) {
           model1.addRow(new Object[]{BookAction.book.get(index).getBookId(),
               BookAction.book.get(index).getBookName(),BookAction.book.get(index).getAuthor(),
               BookAction.book.get(index).getPublisher(),BookAction.book.get(index).getYearOfPublication()}); 
           index++;
        }
       
    }//GEN-LAST:event_jbViewBooksActionPerformed

    private void bt_displayMyBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_displayMyBooksActionPerformed
         int index = 0;
       
        DefaultTableModel model2 = (DefaultTableModel)table_displayMyBook.getModel();
        
        model2.setRowCount(0);
      
        while (User.getMyBooks().size() > index) {
           model2.addRow(new Object[]{User.getMyBooks().get(index).getBookId(),
               User.getMyBooks().get(index).getBookName(),User.getMyBooks().get(index).getAuthor(),
               User.getMyBooks().get(index).getPublisher(),User.getMyBooks().get(index).getYearOfPublication()}); 
           index++;
        }
    }//GEN-LAST:event_bt_displayMyBooksActionPerformed

    private void bt_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_returnActionPerformed
       Menu  qr_mes = new Menu(); 
       qr_mes.setVisible(true);
      if(User.getMyBooks().remove(Menu.rb)){
          message2.setText("Book is returned!");
        }
       
       
     
      
    }//GEN-LAST:event_bt_returnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           this.setVisible(false);
           Login log = new Login();
           log.setVisible(true);
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_sortingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sortingActionPerformed
        ta_alphSorting.setText(bookAction.alphabeticalSorting());
    }//GEN-LAST:event_bt_sortingActionPerformed

    private void CloseViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseViewActionPerformed
        // TODO add your handling code here:
        panel_view.setVisible(false);
    }//GEN-LAST:event_CloseViewActionPerformed

    private void CloseGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseGetActionPerformed
        // TODO add your handling code here:
        allBooks.setVisible(false);
    }//GEN-LAST:event_CloseGetActionPerformed

    private void CloseReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseReturnActionPerformed
        // TODO add your handling code here:
        removingBook.setVisible(false);
    }//GEN-LAST:event_CloseReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseGet;
    private javax.swing.JButton CloseReturn;
    private javax.swing.JButton CloseView;
    private javax.swing.JButton addToUser;
    private javax.swing.JPanel allBooks;
    private javax.swing.JButton bt_displayMyBooks;
    private javax.swing.JButton bt_return;
    private javax.swing.JButton bt_sorting;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton jbAddBook;
    private javax.swing.JButton jbRemoveBook;
    private javax.swing.JButton jbSearch;
    private javax.swing.JButton jbViewBooks;
    private javax.swing.JLabel lbSearch;
    private javax.swing.JLabel message1;
    private javax.swing.JLabel message2;
    private javax.swing.JLabel message3;
    private javax.swing.JLabel message4;
    private javax.swing.JPanel panel_view;
    private javax.swing.JPanel removingBook;
    private javax.swing.JTextArea searchedBookInfo;
    private javax.swing.JTextField searchedId;
    private javax.swing.JTextArea ta_alphSorting;
    private javax.swing.JTextArea ta_dispReturnBook;
    private javax.swing.JTextArea ta_displayuserinfo;
    private javax.swing.JTable table_displayAllBooks;
    private javax.swing.JTable table_displayMyBook;
    // End of variables declaration//GEN-END:variables
}
